import Foundation

/// Command bar strings: English in the source, Italian here (registered at start).
@MainActor
enum CommandText {
    static func t(_ s: String) -> String { L10n.tr(s) }

    static let italian: [String: String] = [
        "Command bar": "Barra dei comandi",
        "Search apps, commands, math…": "Cerca app, comandi, calcoli…",
        "Suggested": "Suggeriti",
        "Recent": "Recenti",
        "No results": "Nessun risultato",
        "Try": "Prova",
        "Application": "App",
        "Calculator": "Calcolatrice",
        "Units": "Unità",
        "Currency": "Valute",
        "Web": "Web",
        "System": "Sistema",
        "Open": "Apri",
        "Run": "Esegui",
        "Copy": "Copia",
        "Quit": "Esci",
        "Search": "Cerca",
        "Show in Finder": "Mostra nel Finder",
        "Copy expression": "Copia l’espressione",
        "Copy with unit": "Copia con l’unità",
        "Copy with currency": "Copia con la valuta",
        "Copy link": "Copia il link",
        "Open %@": "Apri %@",
        "Search Google for “%@”": "Cerca “%@” su Google",
        "Fetching exchange rates…": "Scarico i tassi di cambio…",
        "Exchange rates unavailable offline": "Tassi di cambio non disponibili offline",
        "No rate for %@": "Nessun tasso per %@",
        "Euro foreign exchange reference rates (ECB)": "Tassi di cambio di riferimento dell’euro (BCE)",
        "ECB rates of %@": "tassi BCE del %@",
        "offline": "offline",
        "Glancy Settings": "Impostazioni di Glancy",
        "Command Bar Settings": "Impostazioni della barra dei comandi",
        "Quit Glancy": "Esci da Glancy",
        "Lock Screen": "Blocca schermo",
        "Sleep": "Stop",
        "Turn Off Displays": "Spegni gli schermi",
        "Launcher, calculator, every action": "Avvio app, calcoli, ogni azione",
        // Settings
        "Opens the bar from anywhere": "Apre la barra da qualunque app",
        "Applications": "Applicazioni",
        "Launch and reveal apps": "Apri e mostra le app",
        "Arithmetic, %, hex and binary": "Aritmetica, %, esadecimale e binario",
        "Length, weight, temperature, data, time…": "Lunghezze, pesi, temperature, dati, tempo…",
        "Exchange rates": "Tassi di cambio",
        "Fetched from the ECB only when you type a currency": "Scaricati dalla BCE solo quando scrivi una valuta",
        "Web search": "Ricerca web",
        "Last row: search Google in your browser": "Ultima riga: cerca su Google nel browser",
        "History": "Cronologia",
        "Ranking learns from what you open": "L’ordine impara da ciò che apri",
        "%d remembered": "%d ricordati",
        "Clear": "Cancella",
        "Clear history?": "Cancellare la cronologia?",
        "Results": "Risultati",
        "Esc clears, then closes": "Esc svuota, poi chiude",
    ]
}
