import AppKit
import CryptoKit
import ImageIO
import UniformTypeIdentifiers

// Reading the pasteboard (a cheap snapshot on main), deciding what it is and whether we may keep
// it (privacy), and writing an item back marked as ours.

extension NSPasteboard.PasteboardType {
    /// Put on everything Glancy writes, so it is never captured back.
    static let glancyOwn = NSPasteboard.PasteboardType("ai.glancy.clipboard.own")
    // nspasteboard.org conventions.
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}

/// What was on the pasteboard, copied out on main in one go. Image bytes are raw (any size);
/// they are downsampled later, off main.
public struct PasteboardSnapshot: Sendable {
    public var changeCount: Int
    public var types: [String]
    public var string: String?
    public var rtf: Data?
    public var urlString: String?
    public var image: Data?
    public var fileURLs: [URL]

    public init(changeCount: Int = 0, types: [String], string: String? = nil, rtf: Data? = nil,
                urlString: String? = nil, image: Data? = nil, fileURLs: [URL] = []) {
        self.changeCount = changeCount; self.types = types; self.string = string; self.rtf = rtf
        self.urlString = urlString; self.image = image; self.fileURLs = fileURLs
    }

    static let imageTypes: [NSPasteboard.PasteboardType] = [.png, .tiff, .init("public.jpeg"), .init("public.heic")]

    /// Reads only what the classification needs. Skipped items stop at the type list.
    @MainActor
    public static func read(_ pb: NSPasteboard) -> PasteboardSnapshot {
        let types = (pb.types ?? []).map(\.rawValue)
        var snap = PasteboardSnapshot(changeCount: pb.changeCount, types: types)
        guard ClipboardPrivacy.markerSkip(types) == nil else { return snap }
        if types.contains(NSPasteboard.PasteboardType.fileURL.rawValue) {
            let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL]
            snap.fileURLs = urls ?? []
        }
        snap.string = pb.string(forType: .string)
        snap.urlString = pb.string(forType: .URL)
        if types.contains(NSPasteboard.PasteboardType.rtf.rawValue) { snap.rtf = pb.data(forType: .rtf) }
        if snap.fileURLs.isEmpty, let t = imageTypes.first(where: { types.contains($0.rawValue) }) {
            snap.image = pb.data(forType: t)
        }
        return snap
    }
}

public enum SkipReason: Equatable, Sendable {
    case own, concealed, transient, autoGenerated, passwordManager, excludedApp, paused, empty
}

/// The privacy rules (SPEC §3 Clipboard).
public enum ClipboardPrivacy {
    /// Password managers, by bundle ID: anything copied while one is frontmost is never kept.
    public static let passwordManagers: Set<String> = [
        "com.agilebits.onepassword7", "com.agilebits.onepassword-osx", "com.1password.1password",
        "com.agilebits.onepassword4",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess", "com.apple.Passwords",
        "com.lastpass.LastPass", "com.lastpass.lastpassmacdesktop",
        "com.dashlane.Dashlane", "com.dashlane.dashlanephonefinal",
        "me.proton.pass.electron", "ch.protonmail.pass",
        "org.keepassxc.keepassxc",
    ]

    /// Markers that end the decision at the type list.
    static func markerSkip(_ types: [String]) -> SkipReason? {
        let set = Set(types)
        if set.contains(NSPasteboard.PasteboardType.glancyOwn.rawValue) { return .own }
        if set.contains(NSPasteboard.PasteboardType.concealed.rawValue) { return .concealed }
        if set.contains(NSPasteboard.PasteboardType.transient.rawValue) { return .transient }
        if set.contains(NSPasteboard.PasteboardType.autoGenerated.rawValue) { return .autoGenerated }
        // Older private conventions for the same idea.
        if set.contains("com.agilebits.onepassword") || set.contains("de.petermaurer.TransientPasteboardType")
            || set.contains("Pasteboard generator type") || set.contains("com.typeit4me.clipping") {
            return .transient
        }
        return nil
    }

    public static func skip(types: [String], source: String?, excluded: Set<String>, paused: Bool) -> SkipReason? {
        if let m = markerSkip(types) { return m }
        if paused { return .paused }
        if let source {
            if passwordManagers.contains(source) { return .passwordManager }
            if excluded.contains(source) { return .excludedApp }
        }
        return nil
    }
}

/// A captured item before its blobs exist.
public struct ClipDraft: Sendable, Equatable {
    public var kind: ClipKind
    public var text: String
    public var rtf: Data?
    public var image: Data?
    public var fileURLs: [URL]
    public var signature: String
}

public enum ClipboardClassifier {
    /// What the snapshot is, or why it is not kept.
    public static func classify(_ s: PasteboardSnapshot, source: String?, excluded: Set<String> = [],
                                paused: Bool = false) -> Result<ClipDraft, SkipError> {
        if let reason = ClipboardPrivacy.skip(types: s.types, source: source, excluded: excluded, paused: paused) {
            return .failure(SkipError(reason: reason))
        }
        if !s.fileURLs.isEmpty {
            let paths = s.fileURLs.map(\.path).joined(separator: "\n")
            return .success(ClipDraft(kind: .files, text: paths, fileURLs: s.fileURLs, signature: hash("files", paths)))
        }
        // The source's own preference order decides between text and an image (Office puts a
        // picture of copied text after the text; "Copy Image" puts the image first).
        let imageFirst: Bool = {
            let imageRaw = Set(PasteboardSnapshot.imageTypes.map(\.rawValue))
            let textRaw: Set<String> = [NSPasteboard.PasteboardType.string.rawValue, NSPasteboard.PasteboardType.rtf.rawValue,
                                        NSPasteboard.PasteboardType.URL.rawValue, NSPasteboard.PasteboardType.html.rawValue]
            let first = s.types.first { imageRaw.contains($0) || textRaw.contains($0) }
            return first.map(imageRaw.contains) ?? false
        }()
        let string = s.string.flatMap { $0.isEmpty ? nil : $0 }
        if let image = s.image, imageFirst || string == nil {
            return .success(ClipDraft(kind: .image, text: "", image: image, fileURLs: [], signature: hash("image", image)))
        }
        if let url = urlText(url: s.urlString, string: string) {
            return .success(ClipDraft(kind: .url, text: url, fileURLs: [], signature: hash("text", url)))
        }
        guard let string, !string.allSatisfy(\.isWhitespace) else { return .failure(SkipError(reason: .empty)) }
        if let rtf = s.rtf, rtf.count <= ClipLimits.rtfBytes {
            return .success(ClipDraft(kind: .richText, text: string, rtf: rtf, fileURLs: [], signature: hash("text", string)))
        }
        return .success(ClipDraft(kind: .text, text: string, fileURLs: [], signature: hash("text", string)))
    }

    public struct SkipError: Error, Equatable { public let reason: SkipReason }

    /// A single web/mail URL and nothing else.
    static func urlText(url: String?, string: String?) -> String? {
        let candidate = (string ?? url)?.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let candidate, !candidate.isEmpty, candidate.count < 4096,
              !candidate.contains(where: \.isWhitespace),
              let u = URL(string: candidate), let scheme = u.scheme?.lowercased(),
              ["http", "https", "ftp", "mailto"].contains(scheme),
              scheme == "mailto" || u.host != nil else { return nil }
        return candidate
    }

    // Text and rich text share a signature space: the same words re-copied with or without
    // styling are one item.
    static func hash(_ space: String, _ text: String) -> String { hash(space, Data(text.utf8)) }
    static func hash(_ space: String, _ data: Data) -> String {
        var h = SHA256()
        h.update(data: Data(space.utf8))
        h.update(data: data)
        return h.finalize().prefix(16).map { String(format: "%02x", $0) }.joined()
    }
}

/// Writes an item back to a pasteboard, with our marker.
public enum ClipboardWriter {
    @MainActor @discardableResult
    public static func write(_ item: ClipItem, blobs: URL, to pb: NSPasteboard) -> Int {
        pb.clearContents()
        switch item.kind {
        case .files:
            pb.writeObjects(item.fileURLs as [NSURL])
        case .image:
            if let name = item.imageBlob, let data = try? Data(contentsOf: blobs.appendingPathComponent(name)) {
                pb.setData(data, forType: name.hasSuffix(".png") ? .png : NSPasteboard.PasteboardType("public.heic"))
                // TIFF too: older apps paste only that.
                if let tiff = NSImage(data: data)?.tiffRepresentation { pb.setData(tiff, forType: .tiff) }
            }
        case .url:
            pb.setString(item.text, forType: .string)
            pb.setString(item.text, forType: .URL)
        case .text, .richText:
            let full = item.textBlob.flatMap { try? String(contentsOf: blobs.appendingPathComponent($0), encoding: .utf8) } ?? item.text
            if let name = item.rtfBlob, let rtf = try? Data(contentsOf: blobs.appendingPathComponent(name)) {
                pb.setData(rtf, forType: .rtf)
            }
            pb.setString(full, forType: .string)
        }
        pb.setData(Data(), forType: .glancyOwn)
        return pb.changeCount
    }
}

/// Image downsampling (CGImageSource thumbnail, never a full decode) and encoding.
public enum ClipImage {
    /// The image at ≤ `maxPixels` on its longest side, encoded PNG (or HEIC when the PNG would
    /// exceed `maxBytes`). Nil when the data is not an image.
    public static func downsample(_ data: Data, maxPixels: Int = ClipLimits.imagePixels,
                                  maxBytes: Int = ClipLimits.imageBytes) -> (data: Data, ext: String, size: CGSize)? {
        guard let cg = thumbnail(data, maxPixels: maxPixels) else { return nil }
        let size = CGSize(width: cg.width, height: cg.height)
        if let png = encode(cg, UTType.png, quality: nil), png.count <= maxBytes { return (png, "png", size) }
        for q in [0.8, 0.6, 0.4] {
            if let heic = encode(cg, UTType.heic, quality: q), heic.count <= maxBytes { return (heic, "heic", size) }
        }
        return nil
    }

    public static func thumbnail(_ data: Data, maxPixels: Int) -> CGImage? {
        guard let src = CGImageSourceCreateWithData(data as CFData, [kCGImageSourceShouldCache: false] as CFDictionary) else { return nil }
        return thumbnail(src, maxPixels: maxPixels)
    }

    public static func thumbnail(url: URL, maxPixels: Int) -> CGImage? {
        guard let src = CGImageSourceCreateWithURL(url as CFURL, [kCGImageSourceShouldCache: false] as CFDictionary) else { return nil }
        return thumbnail(src, maxPixels: maxPixels)
    }

    private static func thumbnail(_ src: CGImageSource, maxPixels: Int) -> CGImage? {
        let opts: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceShouldCacheImmediately: true,
            kCGImageSourceThumbnailMaxPixelSize: maxPixels,
        ]
        return CGImageSourceCreateThumbnailAtIndex(src, 0, opts as CFDictionary)
    }

    static func encode(_ image: CGImage, _ type: UTType, quality: Double?) -> Data? {
        let out = NSMutableData()
        guard let dest = CGImageDestinationCreateWithData(out, type.identifier as CFString, 1, nil) else { return nil }
        var props: [CFString: Any] = [:]
        if let quality { props[kCGImageDestinationLossyCompressionQuality] = quality }
        CGImageDestinationAddImage(dest, image, props as CFDictionary)
        guard CGImageDestinationFinalize(dest) else { return nil }
        return out as Data
    }
}
