import Foundation

/// Italian for the Notes module's strings (the English literal is the key), merged into `L10n`
/// at start.
enum NotesText {
    static let italian: [String: String] = [
        "Notes": "Note",
        "Search": "Cerca",
        "New note": "Nuova nota",
        "Open notes": "Apri le note",
        "No matches": "Nessun risultato",
        "No notes yet": "Ancora nessuna nota",
        "Edited %@": "Modificata %@",
        "Yesterday": "Ieri",
        "Add a checklist item": "Aggiungi una voce da spuntare",
        "Pin to Home": "Fissa nella Home",
        "Unpin from Home": "Togli dalla Home",
        "Copy": "Copia",
        "Share…": "Condividi…",
        "Open in Notes": "Apri in Note",
        "Send to…": "Invia a…",
        "Delete note": "Elimina la nota",
        "Delete?": "Eliminare?",
        "Quick notes": "Note rapide",
        "Add to %@: %@": "Aggiungi a %@: %@",
        "Added to %@": "Aggiunto a %@",
        "A new line at the end of the note": "Una riga nuova in fondo alla nota",
        "Quick note": "Nota rapida",
        "Opens the tab with the cursor in a note": "Apre la scheda con il cursore in una nota",
        "The last note if edited in the past 15 minutes, otherwise a new one.":
            "L'ultima nota se modificata negli ultimi 15 minuti, altrimenti una nuova.",
        "Folder": "Cartella",
        "%d notes, plain text (.md)": "%d note, testo semplice (.md)",
        "%d notes": "%d note",
        "Show in Finder": "Mostra nel Finder",
        "Saved as you type. \"- [ ] \" makes a box you can tick; pin a note to see it on Home.":
            "Salvate mentre scrivi. \"- [ ] \" crea una casella da spuntare; fissa una nota per vederla nella Home.",
        // Voice notes
        "Voice note": "Nota vocale",
        "Voice note %@": "Nota vocale %@",
        "Voice notes": "Note vocali",
        "Voice note saved": "Nota vocale salvata",
        "Record voice note": "Registra nota vocale",
        "Stop recording": "Ferma la registrazione",
        "Cancel recording": "Annulla la registrazione",
        "Recording": "Registrazione",
        "Saving…": "Salvataggio…",
        "Stops at %d min": "Si ferma a %d min",
        "Discard": "Scarta",
        "Stop": "Ferma",
        "Stop and save": "Ferma e salva",
        "Open Settings": "Apri Impostazioni",
        "Unmute and record": "Riattiva e registra",
        "OK": "OK",
        "Not now": "Non ora",
        "Microphone access is off": "Accesso al microfono disattivato",
        "Mic muted — unmute to record": "Microfono silenziato — riattivalo per registrare",
        "Couldn't record": "Impossibile registrare",
        "Glancy needs the microphone to record voice notes. Turn it on in System Settings → Privacy & Security → Microphone.":
            "Glancy usa il microfono per registrare le note vocali. Attivalo in Impostazioni di Sistema → Privacy e sicurezza → Microfono.",
        "Your microphone is muted, so a recording would be silent.":
            "Il microfono è silenziato, quindi la registrazione sarebbe muta.",
        "No microphone could be opened. Check the input in System Settings → Sound.":
            "Nessun microfono disponibile. Controlla l'ingresso in Impostazioni di Sistema → Suono.",
        "Turn voice notes into text?": "Trascrivere le note vocali?",
        "On this Mac only: the audio never leaves it.": "Solo su questo Mac: l'audio non esce mai.",
        "Transcribe": "Trascrivi",
        "Transcribing…": "Trascrizione…",
        "Pause": "Pausa",
        "Play": "Riproduci",
        "Playback speed": "Velocità di riproduzione",
        "Drag the recording to Finder, Mail or Messages": "Trascina la registrazione nel Finder, in Mail o in Messaggi",
        "Share recording…": "Condividi la registrazione…",
        "Show recording in Finder": "Mostra la registrazione nel Finder",
        "Starts and stops a recording from anywhere": "Avvia e ferma una registrazione da qualsiasi app",
        "Longest recording": "Durata massima",
        "%d min": "%d min",
        "Recordings are saved as .m4a next to the notes. Speech is turned into text on this Mac; nothing is sent anywhere.":
            "Le registrazioni sono salvate in .m4a accanto alle note. La voce diventa testo su questo Mac; non viene inviato nulla.",
        "Speech Recognition is off in System Settings": "Riconoscimento vocale disattivato in Impostazioni di Sistema",
        "Not available on this Mac for this language": "Non disponibile su questo Mac per questa lingua",
        "On this Mac, after each recording": "Su questo Mac, dopo ogni registrazione",
    ]
}
